@baseurl = http://localhost:3000
@userID = 6a4e9480d2174463fe2909fc
@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2YTU0ZDM2Y2M4ZDRkZDYzNDJmMzNlZTAiLCJpYXQiOjE3ODQ3MTk5OTAsImV4cCI6MTc4NDgwNjM5MH0.PDFcBM-wlZU9ozM0lWGs6voBNloYEFUee1OHW2EFJH4

### Test API
GET {{baseurl}}

### CREATE USER
POST {{baseurl}}/users
content-Type: application/json

{
    "name": "Ankit Chaudhary",
    "email": "ankit.chaudhary@example.com",
    "password": "test123"
}


#### GET ALL USERS
GET {{baseurl}}/users

#### GET USER BY ID
GET {{baseurl}}/users/{{userID}}

### UPDATED BY USER ID
PATCH {{baseurl}}/users/{{userID}}
Content-Type: application/json

{
    "name": "John Doe Updated",
    "email": "johndoe12@example.com"
}

#### DELETE USER BY ID
DELETE {{baseurl}}/users/{{userID}}

#### REGISTER USER BY ID
POST {{baseurl}}/auth/register
content-type: application/json

{
    "name": "Ankit Chaudhary",
    "email": "ankit.ch6@example.com",
    "password": "test123"
}

### LOGIN USER
POST {{baseurl}}/auth/login
Content-Type: application/json

{
  "email": "ankit.ch6@example.com",
    "password": "test123"
}

### CREATE TRIP
POST {{baseurl}}/trips
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "user": "{{userID}}",
  "title": "Trip to the moon",
  "startDate": "2025-12-15",
  "endDate": "2025-12-16",
  "budget": {
    "total": 1000
  },
  "destinations": ["Moon", "Mars", "Jupiter"]
}